remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# title: "End-to-End Automated Guitar Transcription"
# description: "David Kurzend√∂rfer and Christian Hepting"
github:
  repository_url: https://github.com/AutomateGuitarTranscription/guitar-transcription
